version: "3"

services: 
  app:
    image: node:16
    ports: 
      - "6006:6006"
    tty: true
    volumes: 
      - .:/var/www/
    working_dir: /var/www/
    environment: 
      APP_PATH: /var/www